/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../studio/schema.json
export type ExampleBlock = {
  _type: 'exampleBlock'
  title?: string
  text?: string
}

export type Seo = {
  _type: 'seo'
  seoTitle?: string
  seoDescription?: string
  seoKeywords?: Array<string>
  seoImage?: Img
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Img = {
  _type: 'img'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
}

export type Link = {
  _type: 'link'
  label?: string
  linkType?: 'href' | 'custom' | 'anchor'
  href?: string
  custom?: string
  anchor?: string
  openInNewTab?: boolean
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type TranslationMetadata = {
  _id: string
  _type: 'translation.metadata'
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: InternationalizedArrayReference
  schemaTypes?: Array<string>
}

export type InternationalizedArrayReference = Array<
  {
    _key: string
  } & InternationalizedArrayReferenceValue
>

export type HomepageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'homepage'
}

export type HeaderReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'header'
}

export type FooterReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'footer'
}

export type SettingsReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'settings'
}

export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue'
  value?: HomepageReference | HeaderReference | FooterReference | SettingsReference
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language: string
  title?: string
  description?: string
  ogImage?: Img
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language: string
}

export type Header = {
  _id: string
  _type: 'header'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language: string
}

export type Homepage = {
  _id: string
  _type: 'homepage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language: string
  title?: string
  slug: Slug
  seo?: Seo
  pageBuilder?: Array<
    {
      _key: string
    } & ExampleBlock
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | ExampleBlock
  | Seo
  | SanityImageAssetReference
  | Img
  | Link
  | MediaTag
  | Slug
  | TranslationMetadata
  | InternationalizedArrayReference
  | HomepageReference
  | HeaderReference
  | FooterReference
  | SettingsReference
  | InternationalizedArrayReferenceValue
  | Settings
  | Footer
  | Header
  | Homepage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings" && language == $lang][0]{    title,    description,    ogImage{  asset,  hotspot,  crop,  alt}  }
export type SettingsQueryResult = {
  title: string | null
  description: string | null
  ogImage: {
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: headerQuery
// Query: *[_type == "header" && language == $lang][0]{    _id,    _type,  }
export type HeaderQueryResult = {
  _id: string
  _type: 'header'
} | null

// Source: sanity/lib/queries.ts
// Variable: footerQuery
// Query: *[_type == "footer" && language == $lang][0]{    _id,    _type,  }
export type FooterQueryResult = {
  _id: string
  _type: 'footer'
} | null

// Source: sanity/lib/queries.ts
// Variable: homepageQuery
// Query: *[_type == "homepage" && language == $lang][0]{    _id,    _type,    title,    seo{      seoTitle,      seoDescription,      seoImage{  asset,  hotspot,  crop,  alt},    },    "pageBuilder": pageBuilder[]{  ...,  _type == 'exampleBlock' => {    ...,    title,    text  }}  }
export type HomepageQueryResult = {
  _id: string
  _type: 'homepage'
  title: string | null
  seo: {
    seoTitle: string | null
    seoDescription: string | null
    seoImage: {
      asset: SanityImageAssetReference | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
  } | null
  pageBuilder: Array<{
    _key: string
    _type: 'exampleBlock'
    title: string | null
    text: string | null
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: sitemapDataQuery
// Query: *[defined(slug.current) && language == $lang]{    "slug": slug.current,    _type,    _updatedAt  }
export type SitemapDataQueryResult = Array<{
  slug: string
  _type: 'homepage'
  _updatedAt: string
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "settings" && language == $lang][0]{\n    title,\n    description,\n    ogImage{\n  asset,\n  hotspot,\n  crop,\n  alt\n}\n  }\n': SettingsQueryResult
    '\n  *[_type == "header" && language == $lang][0]{\n    _id,\n    _type,\n  }\n': HeaderQueryResult
    '\n  *[_type == "footer" && language == $lang][0]{\n    _id,\n    _type,\n  }\n': FooterQueryResult
    '\n  *[_type == "homepage" && language == $lang][0]{\n    _id,\n    _type,\n    title,\n    seo{\n      seoTitle,\n      seoDescription,\n      seoImage{\n  asset,\n  hotspot,\n  crop,\n  alt\n},\n    },\n    "pageBuilder": pageBuilder[]{\n  ...,\n  _type == \'exampleBlock\' => {\n    ...,\n    title,\n    text\n  }\n}\n  }\n': HomepageQueryResult
    '\n  *[defined(slug.current) && language == $lang]{\n    "slug": slug.current,\n    _type,\n    _updatedAt\n  }\n': SitemapDataQueryResult
  }
}
