/**
 * Sanity CLI Configuration for Frontend
 * This configuration is specifically for running typegen in the frontend workspace
 * Learn more: https://www.sanity.io/docs/cli
 */

import {defineCliConfig} from 'sanity/cli'

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || ''
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || 'production'

export default defineCliConfig({
  api: {
    projectId,
    dataset,
  },

  /**
   * TypeGen configuration
   * Generates TypeScript types from the Studio schema for use in the frontend
   */
  typegen: {
    // Path to scan for GROQ queries in the frontend
    path: './sanity/**/*.{ts,tsx,js,jsx}',
    // Schema file location (generated by the studio)
    schema: '../studio/schema.json',
    // Output file for generated types
    generates: './sanity.types.ts',
    // Overload Sanity client methods with generated types
    overloadClientMethods: true,
  },
})
